package com.folio.cv.template

import com.folio.cv.model.SectionType
import com.folio.cv.template.FontFamilyId.DM_SANS
import com.folio.cv.template.FontFamilyId.GARAMOND
import com.folio.cv.template.FontFamilyId.LATO
import com.folio.cv.template.FontFamilyId.MANROPE
import com.folio.cv.template.FontFamilyId.PLEX_SANS
import com.folio.cv.template.FontFamilyId.POPPINS
import com.folio.cv.template.FontFamilyId.SOURCE_SERIF
import com.folio.cv.template.Weight.BOLD
import com.folio.cv.template.Weight.LIGHT
import com.folio.cv.template.Weight.MEDIUM
import com.folio.cv.template.Weight.REGULAR

/**
 * The second collection: photo headers, full-height sidebars, timelines and icon contacts,
 * in the spirit of contemporary designer CVs.
 */
internal object DesignedTemplates {

    private val modernAccents = listOf(
        0xFF2B2B2B, // Charcoal
        0xFF2B3A55, // Navy
        0xFF2F5D50, // Deep green
        0xFF8C5A3C, // Caramel
        0xFF7A2E3A, // Wine
        0xFF3A5A8C, // Denim
    )

    /** For templates whose sidebar is filled with the accent: every option carries white text. */
    private val darkAccents = listOf(
        0xFF2E3A4E, // Midnight navy
        0xFF26282B, // Charcoal
        0xFF1F3D33, // Forest
        0xFF3D2A3F, // Plum
        0xFF34495E, // Slate
        0xFF4A1F24, // Oxblood
    )

    private val engineeringAccents = listOf(
        0xFF1F4E79, // Blueprint
        0xFF2C3E50, // Steel
        0xFFB4501E, // Safety copper
        0xFF0B6E4F, // Machine green
        0xFF1D1D1F, // Graphite
    )

    private val sidebarWithEducation = TemplateSpec.DEFAULT_SIDEBAR + SectionType.EDUCATION

    private fun poppins(nameSize: Float = 27f, nameCaps: Boolean = false, sectionCaps: Boolean = true, sectionSize: Float = 10.5f) = Typography(
        name = TypeRole(POPPINS, BOLD, nameSize, caps = nameCaps, tracking = if (nameCaps) 0.04f else 0f, lineHeight = 1.08f),
        headline = TypeRole(POPPINS, REGULAR, 12f, tracking = 0.12f),
        section = TypeRole(POPPINS, BOLD, sectionSize, caps = sectionCaps, tracking = if (sectionCaps) 0.06f else 0f),
        entryTitle = TypeRole(POPPINS, BOLD, 10.2f),
        body = TypeRole(POPPINS, REGULAR, 9.4f, lineHeight = 1.48f),
        meta = TypeRole(POPPINS, REGULAR, 8.4f),
    )

    private fun lato(nameSize: Float = 30f, nameWeight: Weight = BOLD) = Typography(
        name = TypeRole(LATO, nameWeight, nameSize, tracking = -0.01f, lineHeight = 1.08f),
        headline = TypeRole(LATO, REGULAR, 12.5f, tracking = 0.04f),
        section = TypeRole(LATO, BOLD, 9.6f, caps = true, tracking = 0.16f),
        entryTitle = TypeRole(LATO, BOLD, 10.6f),
        body = TypeRole(LATO, REGULAR, 10f, lineHeight = 1.42f),
        meta = TypeRole(LATO, REGULAR, 9f),
    )

    val all: List<TemplateSpec> = listOf(
        TemplateSpec(
            id = "portrait",
            name = "Portrait",
            tagline = "A framed portrait beside your name, two calm columns below.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SIDEBAR_LEFT,
            header = HeaderStyle.PHOTO_LEFT,
            heading = HeadingStyle.CAPS_TRACKED,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.BULLETS,
            type = poppins(nameSize = 27f, nameCaps = true),
            palette = Palette(ink = 0xFF2B2B2B, secondary = 0xFF6B6B6B, accent = 0xFF2B2B2B),
            accentOptions = modernAccents,
            marginPt = 44f,
            sidebarFraction = 0.31f,
            photo = PhotoShape.CIRCLE,
            contactStyle = ContactStyle.ICONS,
            sidebarSections = sidebarWithEducation,
            sidebarBackground = false,
            columnRule = true,
            headerRule = HeaderRule.HAIRLINE,
            showEntryTags = false,
        ),
        TemplateSpec(
            id = "atrium",
            name = "Atrium",
            tagline = "A soft grey sidebar holds your photo, story and skills.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SIDEBAR_LEFT,
            header = HeaderStyle.SIDEBAR,
            heading = HeadingStyle.CAPS_TRACKED,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.BULLETS,
            type = poppins(nameSize = 31f).let { it.copy(headline = it.headline.copy(sizePt = 11.5f, tracking = 0.14f)) },
            palette = Palette(ink = 0xFF262626, secondary = 0xFF6B6B6B, accent = 0xFF262626, sidebarFill = 0xFFF1F1F0),
            accentOptions = modernAccents,
            marginPt = 40f,
            sidebarFraction = 0.34f,
            photo = PhotoShape.CIRCLE,
            nameStyle = NameStyle.BOLD_LIGHT,
            contactStyle = ContactStyle.ICONS,
            sidebarSections = sidebarWithEducation + SectionType.SUMMARY,
            showEntryTags = false,
        ),
        TemplateSpec(
            id = "linea",
            name = "Linea",
            tagline = "Thin, wide-set capitals and a fine timeline. Quietly luxurious.",
            category = TemplateCategory.MINIMAL,
            atsRating = AtsRating.VERY_GOOD,
            layout = LayoutKind.SIDEBAR_LEFT,
            header = HeaderStyle.LEFT,
            heading = HeadingStyle.CAPS_TRACKED,
            dates = DateStyle.TIMELINE,
            skills = SkillStyle.BULLETS,
            type = Typography(
                name = TypeRole(LATO, LIGHT, 34f, caps = true, tracking = 0.16f, lineHeight = 1.06f),
                headline = TypeRole(LATO, REGULAR, 13f, tracking = 0.16f),
                section = TypeRole(LATO, REGULAR, 11f, caps = true, tracking = 0.3f),
                entryTitle = TypeRole(LATO, BOLD, 10.4f),
                body = TypeRole(LATO, REGULAR, 9.8f, lineHeight = 1.42f),
                meta = TypeRole(LATO, REGULAR, 8.8f),
            ),
            palette = Palette(ink = 0xFF262626, secondary = 0xFF666666, rule = 0xFFE4E4E4, accent = 0xFF262626),
            accentOptions = modernAccents,
            marginPt = 46f,
            sidebarFraction = 0.33f,
            nameStyle = NameStyle.STACKED,
            contactStyle = ContactStyle.SIDEBAR,
            sidebarSections = sidebarWithEducation,
            sidebarBackground = false,
            summaryFullWidth = true,
            headerRule = HeaderRule.THICK,
            showEntryTags = false,
        ),
        TemplateSpec(
            id = "midnight",
            name = "Midnight",
            tagline = "A deep navy sidebar, a portrait and a connected timeline.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SIDEBAR_LEFT,
            header = HeaderStyle.SIDEBAR,
            heading = HeadingStyle.UNDERLINE,
            dates = DateStyle.TIMELINE,
            skills = SkillStyle.BULLETS,
            type = poppins(nameSize = 27f, sectionCaps = false, sectionSize = 13f)
                .let { it.copy(name = it.name.copy(tracking = 0.02f), headline = it.headline.copy(tracking = 0.18f)) },
            palette = Palette(
                ink = 0xFF1F2733, secondary = 0xFF5E6673, rule = 0xFFC9CED6,
                accent = 0xFF2E3A4E, sidebarFill = 0xFF2E3A4E, onSidebar = 0xFFFFFFFF,
            ),
            accentOptions = darkAccents,
            marginPt = 38f,
            sidebarFraction = 0.33f,
            photo = PhotoShape.CIRCLE,
            contactStyle = ContactStyle.SIDEBAR,
            sidebarSections = sidebarWithEducation,
            showEntryTags = false,
        ),
        TemplateSpec(
            id = "sloane",
            name = "Sloane",
            tagline = "Charcoal sidebar on the right, crisp Lato on the left.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.VERY_GOOD,
            layout = LayoutKind.SIDEBAR_RIGHT,
            header = HeaderStyle.SIDEBAR,
            heading = HeadingStyle.CAPS_TRACKED,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.TAGS,
            type = lato(nameSize = 32f),
            palette = Palette(accent = 0xFF26282B, sidebarFill = 0xFF26282B, onSidebar = 0xFFFFFFFF),
            accentOptions = darkAccents,
            marginPt = 42f,
            sidebarFraction = 0.32f,
            contactStyle = ContactStyle.SIDEBAR,
            sidebarSections = sidebarWithEducation,
        ),
        TemplateSpec(
            id = "meridian",
            name = "Meridian",
            tagline = "Centred and symmetrical, with an optional portrait on top.",
            category = TemplateCategory.CLASSIC,
            atsRating = AtsRating.VERY_GOOD,
            layout = LayoutKind.SINGLE,
            header = HeaderStyle.CENTER,
            heading = HeadingStyle.CENTERED_RULE,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.BULLETS,
            type = Typography(
                name = TypeRole(LATO, LIGHT, 32f, caps = true, tracking = 0.2f, lineHeight = 1.1f),
                headline = TypeRole(LATO, REGULAR, 10.5f, caps = true, tracking = 0.22f),
                section = TypeRole(LATO, BOLD, 9.6f, caps = true, tracking = 0.24f),
                entryTitle = TypeRole(LATO, BOLD, 10.6f),
                body = TypeRole(LATO, REGULAR, 10f, lineHeight = 1.42f),
                meta = TypeRole(LATO, REGULAR, 9f),
            ),
            palette = Palette(ink = 0xFF2A2623, secondary = 0xFF6F6760, rule = 0xFFD9D2CA, accent = 0xFF8C6D4F),
            accentOptions = listOf(0xFF8C6D4F, 0xFF2A2623, 0xFF2B3A55, 0xFF2F5D50, 0xFF7A2E3A),
            marginPt = 54f,
            photo = PhotoShape.CIRCLE,
        ),
        TemplateSpec(
            id = "harbor",
            name = "Harbor",
            tagline = "A teal header band with portrait, and a timeline beneath.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SINGLE,
            header = HeaderStyle.BAND,
            heading = HeadingStyle.UNDERLINE,
            dates = DateStyle.TIMELINE,
            skills = SkillStyle.TAGS,
            type = poppins(nameSize = 28f, sectionCaps = false, sectionSize = 12.5f),
            palette = Palette(ink = 0xFF1E2B30, secondary = 0xFF5D6A70, accent = 0xFF1F5A66, bandFill = 0xFF1F4D5A),
            accentOptions = listOf(0xFF1F5A66, 0xFF2B3A55, 0xFF2F5D50, 0xFF7A2E3A, 0xFF2B2B2B),
            marginPt = 46f,
            photo = PhotoShape.CIRCLE,
        ),
        TemplateSpec(
            id = "sage",
            name = "Sage",
            tagline = "A pale green sidebar, a two-weight name and gentle accents.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SIDEBAR_LEFT,
            header = HeaderStyle.SIDEBAR,
            heading = HeadingStyle.ACCENT_BAR,
            dates = DateStyle.BELOW,
            skills = SkillStyle.BULLETS,
            type = Typography(
                name = TypeRole(DM_SANS, BOLD, 31f, tracking = -0.02f, lineHeight = 1.04f),
                headline = TypeRole(DM_SANS, REGULAR, 12.5f),
                section = TypeRole(DM_SANS, BOLD, 9f, caps = true, tracking = 0.14f),
                entryTitle = TypeRole(DM_SANS, BOLD, 10.6f),
                body = TypeRole(DM_SANS, REGULAR, 9.9f, lineHeight = 1.42f),
                meta = TypeRole(DM_SANS, REGULAR, 8.9f),
            ),
            palette = Palette(ink = 0xFF1F2A22, secondary = 0xFF5F6B62, accent = 0xFF4F6F52, sidebarFill = 0xFFEEF2EC),
            accentOptions = listOf(0xFF4F6F52, 0xFF2B3A55, 0xFF8C5A3C, 0xFF7A2E3A, 0xFF2B2B2B),
            marginPt = 40f,
            sidebarFraction = 0.33f,
            photo = PhotoShape.CIRCLE,
            nameStyle = NameStyle.BOLD_LIGHT,
            contactStyle = ContactStyle.SIDEBAR,
            sidebarSections = sidebarWithEducation,
        ),
        TemplateSpec(
            id = "linen",
            name = "Linen",
            tagline = "Garamond and walnut, with a ruled side column for details.",
            category = TemplateCategory.CLASSIC,
            atsRating = AtsRating.VERY_GOOD,
            layout = LayoutKind.SIDEBAR_RIGHT,
            header = HeaderStyle.LEFT,
            heading = HeadingStyle.RULE_BELOW,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.LIST,
            type = Typography(
                name = TypeRole(GARAMOND, MEDIUM, 34f, tracking = -0.01f, lineHeight = 1.05f),
                headline = TypeRole(GARAMOND, REGULAR, 14f, italic = true),
                section = TypeRole(GARAMOND, MEDIUM, 12.5f, caps = true, tracking = 0.1f),
                entryTitle = TypeRole(SOURCE_SERIF, BOLD, 10.4f),
                body = TypeRole(SOURCE_SERIF, REGULAR, 9.8f, lineHeight = 1.4f),
                meta = TypeRole(SOURCE_SERIF, REGULAR, 9f, italic = true),
            ),
            palette = Palette(ink = 0xFF2A211C, secondary = 0xFF6E625A, rule = 0xFFDCD3CB, accent = 0xFF5C4033),
            accentOptions = listOf(0xFF5C4033, 0xFF1F4E79, 0xFF2F5D50, 0xFF7A2E3A, 0xFF2A211C),
            marginPt = 50f,
            sidebarFraction = 0.3f,
            contactStyle = ContactStyle.SIDEBAR,
            sidebarBackground = false,
            columnRule = true,
            showEntryTags = false,
        ),
        TemplateSpec(
            id = "kepler",
            name = "Kepler",
            tagline = "Steel sidebar for your toolkit and credentials, timeline for your projects.",
            category = TemplateCategory.ENGINEERING,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SIDEBAR_LEFT,
            header = HeaderStyle.SIDEBAR,
            heading = HeadingStyle.UNDERLINE,
            dates = DateStyle.TIMELINE,
            skills = SkillStyle.LIST,
            type = Typography(
                name = TypeRole(PLEX_SANS, BOLD, 26f, tracking = -0.01f, lineHeight = 1.08f),
                headline = TypeRole(PLEX_SANS, REGULAR, 12f, caps = true, tracking = 0.12f),
                section = TypeRole(PLEX_SANS, BOLD, 12f),
                entryTitle = TypeRole(PLEX_SANS, BOLD, 10.4f),
                body = TypeRole(PLEX_SANS, REGULAR, 9.7f, lineHeight = 1.4f),
                meta = TypeRole(PLEX_SANS, REGULAR, 8.8f),
            ),
            palette = Palette(
                ink = 0xFF1C2630, secondary = 0xFF5A6672, rule = 0xFFC6CDD4,
                accent = 0xFF2C3E50, sidebarFill = 0xFF2C3E50, onSidebar = 0xFFFFFFFF,
            ),
            accentOptions = listOf(0xFF2C3E50, 0xFF1F3A5F, 0xFF26282B, 0xFF1F3D33, 0xFF4A1F24),
            marginPt = 38f,
            sidebarFraction = 0.33f,
            photo = PhotoShape.CIRCLE,
            contactStyle = ContactStyle.SIDEBAR,
            sidebarSections = sidebarWithEducation,
        ),
        TemplateSpec(
            id = "gauge",
            name = "Gauge",
            tagline = "Clean single column with icon contacts and room for a headshot.",
            category = TemplateCategory.ENGINEERING,
            atsRating = AtsRating.VERY_GOOD,
            layout = LayoutKind.SINGLE,
            header = HeaderStyle.PHOTO_LEFT,
            heading = HeadingStyle.CAPS_TRACKED,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.INLINE,
            type = lato(nameSize = 28f),
            palette = Palette(accent = 0xFF1F4E79),
            accentOptions = engineeringAccents,
            marginPt = 46f,
            photo = PhotoShape.CIRCLE,
            contactStyle = ContactStyle.ICONS,
            headerRule = HeaderRule.HAIRLINE,
        ),
        TemplateSpec(
            id = "noir",
            name = "Noir",
            tagline = "Black header band, two-weight name. Made to be remembered.",
            category = TemplateCategory.CREATIVE,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SINGLE,
            header = HeaderStyle.BAND,
            heading = HeadingStyle.CAPS_TRACKED,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.TAGS,
            type = poppins(nameSize = 32f).let { it.copy(name = it.name.copy(tracking = -0.01f, lineHeight = 1.02f)) },
            palette = Palette(ink = 0xFF141414, accent = 0xFF141414, bandFill = 0xFF111111),
            accentOptions = listOf(0xFF141414, 0xFF7A2E3A, 0xFF2B3A55, 0xFF2F5D50, 0xFF8C5A3C),
            marginPt = 46f,
            nameStyle = NameStyle.BOLD_LIGHT,
        ),
        TemplateSpec(
            id = "studio",
            name = "Studio",
            tagline = "A blush side panel with a rounded portrait and a timeline.",
            category = TemplateCategory.CREATIVE,
            atsRating = AtsRating.GOOD,
            layout = LayoutKind.SIDEBAR_RIGHT,
            header = HeaderStyle.SIDEBAR,
            heading = HeadingStyle.ACCENT_BAR,
            dates = DateStyle.TIMELINE,
            skills = SkillStyle.TAGS,
            type = poppins(nameSize = 30f).let { it.copy(name = it.name.copy(tracking = -0.01f)) },
            palette = Palette(ink = 0xFF2A2321, secondary = 0xFF6E6461, rule = 0xFFE3D6D1, accent = 0xFFB0574A, sidebarFill = 0xFFF6EEEA),
            accentOptions = listOf(0xFFB0574A, 0xFF7A2E3A, 0xFF2B3A55, 0xFF2F5D50, 0xFF2B2B2B),
            marginPt = 40f,
            sidebarFraction = 0.32f,
            photo = PhotoShape.ROUNDED,
            nameStyle = NameStyle.STACKED,
            contactStyle = ContactStyle.ICONS,
            sidebarSections = sidebarWithEducation,
        ),
        TemplateSpec(
            id = "atlas",
            name = "Atlas",
            tagline = "Rounded portrait, ruled headings and dates in the margin.",
            category = TemplateCategory.MODERN,
            atsRating = AtsRating.VERY_GOOD,
            layout = LayoutKind.SINGLE,
            header = HeaderStyle.PHOTO_LEFT,
            heading = HeadingStyle.UNDERLINE,
            dates = DateStyle.GUTTER,
            skills = SkillStyle.BULLETS,
            type = Typography(
                name = TypeRole(MANROPE, BOLD, 28f, tracking = -0.02f, lineHeight = 1.08f),
                headline = TypeRole(MANROPE, REGULAR, 12.5f),
                section = TypeRole(MANROPE, BOLD, 12f),
                entryTitle = TypeRole(MANROPE, BOLD, 10.4f),
                body = TypeRole(MANROPE, REGULAR, 9.7f, lineHeight = 1.42f),
                meta = TypeRole(MANROPE, REGULAR, 8.8f),
            ),
            palette = Palette(accent = 0xFF3A5A8C),
            accentOptions = modernAccents,
            marginPt = 46f,
            photo = PhotoShape.ROUNDED,
            contactStyle = ContactStyle.ICONS,
        ),
        TemplateSpec(
            id = "clarity",
            name = "Clarity",
            tagline = "Plain, airy and machine-readable, with tidy icon contacts.",
            category = TemplateCategory.MINIMAL,
            atsRating = AtsRating.EXCELLENT,
            layout = LayoutKind.SINGLE,
            header = HeaderStyle.LEFT,
            heading = HeadingStyle.RULE_BELOW,
            dates = DateStyle.RIGHT,
            skills = SkillStyle.INLINE,
            type = lato(nameSize = 30f),
            palette = Palette(accent = 0xFF2B3A55),
            accentOptions = modernAccents,
            marginPt = 50f,
            contactStyle = ContactStyle.ICONS,
            headerRule = HeaderRule.HAIRLINE,
        ),
    )
}
